### ISSUE TITLE
куда делся ратник???

### ISSUE THREAD

**Issue by oliyase** [fetloader/fetloader#2]
я когда использовал лондер было 15 ратников, 17 майнеров и 24 стиллера; а сейчас - 14 ратниклв, 13 майнеров и 22 стиллерай. вапрос: куда делись ратники стиллеры и майнеры????

**Comment by aliveoutside** [comment]
закриптовали

**Comment by rfoxxxy** [comment]
@oliyase хохлам скормили

**Comment by oliyase** [comment]
вот зе фак

**Comment by rfoxxxy** [comment]
@oliyase твоей маме скормили свинье

**Comment by oliyase** [comment]
хах

**Comment by oliyase** [comment]
![IMG_20210611_184854_783](https://user-images.githubusercontent.com/26191412/121713583-b355d380-cae5-11eb-957a-9e1ba59b8c35.jpg)

**Comment by clownless** [comment]
@oliyase справа
